[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.13.2"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[prune]
  go-tests = true
  unused-packages = true
